### ISSUE TITLE
Analyze temporary Codeset table to improve performance in cohort generation

### ISSUE THREAD

**Issue by fqzhao** [OHDSI/circe-be#101]
Hi,

We encountered an issue that a cohort generation won't finish , which is caused by a bad optimization decision made by the query planner of postgresql (11.5 and also 12). 
The Codeset  temporary table is very big in this case (180000+);   After adding ANALYZE VERBOSE CodeSet,The query can produce results in reasonable time.

**Comment by chrisknoll** [comment]
Fixed in #197
