### ISSUE TITLE
User Defined Period Date format

### ISSUE THREAD

**Issue by wivern** [OHDSI/circe-be#103]
When applying a user-defined period illegal SQL might be generated.
That was since SQLRender expects dates in the YYYYMMdd format but
 Atlas provides dates in YYYY-MM-dd format.
The suggestion is to filter out all non-digit symbols from date strings during SQL construction.

**Comment by chrisknoll** [comment]
Actually, SqlRender expects to use DATEFROMPARTS(), so perhaps the fix is to use that syntax from the SQL builder, by parsing out the YYYY-MM-dd format that Circe is storing as the input.
