### ISSUE TITLE
cohort_definition_id should be bigint

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/circe-be#128]
in this script https://github.com/OHDSI/circe-be/blob/a3a785165b268b77b41268db5fdb34f651d924a4/src/test/resources/cohortgeneration/resultsSchema.sql#L2

to be compatible with

https://github.com/OHDSI/CommonDataModel/blob/58f01a2a69b4960a48eb1ebf9ea11a4cae76c841/Sql%20Server/OMOP%20CDM%20Results%20sql%20server.txt#L48

**Comment by chrisknoll** [comment]
The test script for cohort generation reflects the column definitions defined in the WebAPI results DDL:
https://github.com/OHDSI/WebAPI/blob/master/src/main/resources/ddl/results/cohort.sql

We can update the test script if the WebAPI results's schema changes.

**Comment by gowthamrao** [comment]
@chrisknoll would you be ok in making cohort_definition_id BIGINT everywhere? 

For phenotype library project (OHDSI symposium 2020 release), we are planning to define cohortIds as (referrantConceptId * 1000) + a number between (3-999). This would be a BIGINT. There was a discussion (no decision) that this could be a set of 'standard' id's for cohort definitions across all OHDSI software (i.e. maybe it should be part of default set of cohorts instantiated when atlas is deployed).
