### ISSUE TITLE
Cohort exit criteria doesn't right-censor at OBSERVATION_PERIOD_END_DATE

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/circe-be#139]
Expect: (potentially as option?)   COHORT_END_DATE is no greater than OBSERVATION_PERIOD_END_DATE.   If user specified a fixed window that extends past the observation_period_end_date, it should be set to observation_period_end_date.

Actual:  observation_period_end_date not used when you select a fixed window

**Comment by chrisknoll** [comment]
Dupe of #63
