### ISSUE TITLE
Performance optimizations for era building and temp table insertions

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/circe-be#14]
There's 2 performance issues that should be addressed as part of this issue:

1. Inserting into temp tables is slow on MPP systems, so should be replaced with CTAS   with UNION ALL.
2. The cohort collapse (era-fy) logic using the surrogate key from dense_rank() loses distribution hash in MPP environments when joining by group_id instead of the partitioned columns directly.  The partitioned columns is what makes the MPP execution faster, while the group_id causes a 'shuffle move' and 'partition move' between nodes in MPP, introducing overhead.

@gowthamrao , if you don't have a MPP environment to help test this implementation (redshift or microsoft azure/pdw) your review of these changes would still be welcome.

**Comment by gowthamrao** [comment]
You got it! Working on something this week, but I can help
