### ISSUE TITLE
Wrap circe-be in R package?

### ISSUE THREAD

**Issue by schuemie** [OHDSI/circe-be#16]
I think it would be cool if we could wrap circe-be in an R package. That way, OHDSI study package only need to contain the JSON of the relevant cohort definitions, and can generate the SQL on the fly when instantiating those cohorts at a data site (if I understand circe-be correctly). 

(Right now we have to keep both JSON and SQL in our study packages, and that begs the question whether they are in fact the same cohort definitions)

Any objections, suggestions? I would be happy to attempt a first version in a separate branch.

**Comment by gowthamrao** [comment]
@schuemie  I like this idea. May be related to https://github.com/OHDSI/Atlas/issues/511 @jduke99 @fdefalco 

Also related to https://github.com/OHDSI/circe-be/issues/17 . For Business intelligence use cases, we need to go thru the steps of cohort generation and cohort characterization for the same cohort on a periodic basis. On each run, we have to update the dates referenced in the cohort.

@fdefalco @schuemie  if this can somehow be made into an API or microservice, with both a get and post -- it would be very useful. e.g. Atlas is very good, but is complex. One thought is that using API/microservices, we could have a 'simpler' or 'push button' Atlas like system that is targeted for a custom audience. This new tool would use the API and microservices - and so will be easy to manage.

**Comment by schuemie** [comment]
Just so you know, this is something we already do. For example, in [this study package](https://github.com/OHDSI/StudyProtocols/tree/master/AlendronateVsRaloxifene) we import all cohort definitions from ATLAS into the package using the [insertCohortDefinitionSetInPackage command](https://github.com/OHDSI/StudyProtocols/blob/master/AlendronateVsRaloxifene/extras/PackageMaintenance.R#L29), which automatically grabs the cohorts listed [here](https://github.com/OHDSI/StudyProtocols/blob/master/AlendronateVsRaloxifene/inst/settings/CohortsToCreate.csv) and adds both the [JSON](https://github.com/OHDSI/StudyProtocols/tree/master/AlendronateVsRaloxifene/inst/cohorts) and [OHDSI SQL](https://github.com/OHDSI/StudyProtocols/tree/master/AlendronateVsRaloxifene/inst/sql/sql_server) to the package. Any site executing the package then has the appropriate cohorts instantiated using the SQL, making the whole study self-contained.

What we hope to achieve by creating a CirceBe R package is to not have to store both the SQL and the JSON, but only the JSON, and generate the SQL on the fly.
