### ISSUE TITLE
Collapsing magic sometimes fails to merge eligible periods

### ISSUE THREAD

**Issue by xitology** [OHDSI/circe-be#162]
I can reliably reproduce the issue on the cohort 4223659000/4223659003.json from PhenotypeLibrary with synpuf100k dataset running under SQL Server. I also tested it under Postgresql and Redshift, but the issue does not exhibit there.

My testing environment consists of MS SQL Server running in a container mcr.microsoft.com/mssql/server:latest and the synpuf100k dataset, which I created using data files and vocabulary from S3 bucket ohdsi-sample-data/cmsdesynpuf100k/ and ohdsi-sample-data/vocab/.

I used circe-1.9.4.jar to generate a SQL file 4223659003.sqlserver.sql from the cohort definition. See it here: https://gist.github.com/xitology/d275212c8399ae847827d15a0f4980e3#file-4223659003-sqlserver-sql.

It is easy to see that the SQL has a problem because running it several times gives me a varying number of cohort entries:
```
$ sqlcmd -d synpuf100k -i 4223659003.sqlserver.sql
[...]
(93481 rows affected)

$ sqlcmd -d synpuf100k -Q 'select count(*) from cohort where cohort_definition_id = 0'

-----------
      93481

(1 rows affected)
$ sqlcmd -d synpuf100k -i 4223659003.sqlserver.sql
[...]
(93479 rows affected)

$ sqlcmd -d synpuf100k -Q 'select count(*) from cohort where cohort_definition_id = 0'

-----------
      93479

(1 rows affected)
```

When I compare the output from one of the runs with the expected output I generated separately, I see:
```
6×4 DataFrame
 Row │ subject_id  start_date   end_date     definition_id
     │ Int32?      Dates.Date?  Dates.Date?  Int32?
─────┼─────────────────────────────────────────────────────
   1 │    1602995  2009-06-16   2009-06-27               0
   2 │    1602995  2009-06-16   2009-07-30               1
   3 │    1602995  2009-07-01   2009-07-30               0
   4 │    2129660  2008-05-13   2008-05-14               0
   5 │    2129660  2008-05-13   2008-06-16               1
   6 │    2129660  2008-06-13   2008-06-16               0
```
This table shows the difference between the cohort produced by circe (definition_id = 0) and the expected result (definition_id = 1). It is clear that the intervals (2009-06-16, 2009-06-27) and (2009-07-01, 2009-07-30), as well as (2008-05-13, 2008-05-14) and (2008-06-13, 2008-06-16) failed to merge.

I'm not entirely sure what's causing the issue, but I attribute it to the non-deterministic `ORDER BY` clauses in the collapsing query (see https://gist.github.com/xitology/d275212c8399ae847827d15a0f4980e3#file-4223659003-sqlserver-sql-L155-L156):
```
, MAX(start_ordinal) OVER (PARTITION BY person_id ORDER BY event_date, event_type ROWS UNBOUNDED PRECEDING) AS start_ordinal 
, ROW_NUMBER() OVER (PARTITION BY person_id ORDER BY event_date, event_type) AS overall_ord
```
Although the `ORDER BY` clauses are identical, they do not enforce the total order of rows, and there is no guarantee that `MAX(start_ordinal)` and `ROW_NUMBER()` will be calculated with respect to the same row ordering. I tried to verify this by adding `start_ordinal` to make the order stable
```
, MAX(start_ordinal) OVER (PARTITION BY person_id ORDER BY event_date, event_type, start_ordinal ROWS UNBOUNDED PRECEDING) AS start_ordinal 
, ROW_NUMBER() OVER (PARTITION BY person_id ORDER BY event_date, event_type, start_ordinal) AS overall_ord
```
and it apparently fixed the issue. See the updated file here: https://gist.github.com/xitology/d275212c8399ae847827d15a0f4980e3#file-fixed-4223659003-sqlserver-sql.

**Comment by chrisknoll** [comment]
So, unlike #163, the addition of `start_ordinal` is a bit different because start_ordinal in the subquery could sometimes be `NULL` value (when the event_date came from `end_date`s.  so I wonder if there is an issue there.  You confirmed that it did work in your case, but I'm still wondering if ordering on a nullable column is an issue.

I'm not sure how this would impact the `MAX(start_ordinal))` statement: how is the MAX() resulting in the incorrect value if we  don't specify the start_ordinal in the sort?    Or is the problem in the ROW_NUMBER()?   You are probably right that the rows applied for MAX() are somehow not the very same rows as being used in ROW_NUMBER() and therefore lead to strange result.  So we can apply additional logic to the sort to try to get the consistent ordering.

Could you confirm what version is running `mcr.microsoft.com/mssql/server:latest`?  I'm guessing that maybe if it's something like a new version of SQL server, there's some kind of query optimization that I never encountered before.  I've seen this work on SQL 2012-2016.  Not sure if later versions maybe have made special optimizations that are now biting us here.

Great work doing the detective work to identify these issues!  I have a pretty robust [set of tests](https://github.com/OHDSI/circe-be/blob/master/src/test/java/org/ohdsi/circe/cohortdefinition/CohortGeneration_5_0_0_Test.java) but clearly i've missed some cases....granted we only have one test container configured to run the tests on.

Thank you very much for your efforts.

**Comment by xitology** [comment]
> Could you confirm what version is running `mcr.microsoft.com/mssql/server:latest`? I'm guessing that maybe if it's something like a new version of SQL server, there's some kind of query optimization that I never encountered before. I've seen this work on SQL 2012-2016. Not sure if later versions maybe have made special optimizations that are now biting us here.

Here's what `SELECT @@VERSION` reports:
```
$ sqlcmd -Q 'select @@version'
                                                                                                                                                                              
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Microsoft SQL Server 2019 (RTM-CU10) (KB5001090) - 15.0.4123.1 (X64)
	Mar 22 2021 18:10:24
	Copyright (C) 2019 Microsoft Corporation
	Developer Edition (64-bit) on Linux (Ubuntu 20.04.2 LTS) <X64>

(1 rows affected)
```

**Comment by chrisknoll** [comment]
Ok, thanks for the info. I'll arrange to make the necessary changes. Thanks very much for your research on this, it is very helpful in making the correct changes.

**Comment by xitology** [comment]
> I'm not sure how this would impact the `MAX(start_ordinal))` statement: how is the MAX() resulting in the incorrect value if we don't specify the start_ordinal in the sort? Or is the problem in the ROW_NUMBER()? You are probably right that the rows applied for MAX() are somehow not the very same rows as being used in ROW_NUMBER() and therefore lead to strange result. So we can apply additional logic to the sort to try to get the consistent ordering.

FWIW, it's just my guess that the problem is caused by non-deterministic `ORDER BY`. I was surprised that different runs produce different outputs, and was looking for any query fragment which could potentially make the output non-deterministic. The `ORDER BY` clause is the only one I could discover, but it's possible that my change just masked the real issue rather than fixed it.

I tried to manually reconstruct the output cohort for a single patient record. Take patient 1602995. The query produced two intervals (2009-06-16, 2009-06-27) and (2009-07-01, 2009-07-30) instead of expected (2009-06-16, 2009-07-30). Here is the relevant source data from the `#cohort_rows` table:
```
person_id   start_date       end_date
----------- ---------------- ----------------
    1602995       2009-06-16       2009-06-19
    1602995       2009-06-16       2009-06-19
    1602995       2009-07-01       2009-07-04
    1602995       2009-07-01       2009-07-04
    1602995       2009-07-27       2009-07-30
    1602995       2009-07-27       2009-07-30
    1602995       2009-07-27       2009-07-30
    1602995       2009-07-27       2009-07-30
    1602995       2009-07-27       2009-07-30
    1602995       2009-07-27       2009-07-30
    1602995       2009-07-27       2009-07-30
    1602995       2009-07-27       2009-07-30
    1602995       2009-07-27       2009-07-30
    1602995       2009-07-27       2009-07-30
    1602995       2009-07-27       2009-07-30
    1602995       2009-07-27       2009-07-30
    1602995       2009-07-27       2009-07-30
    1602995       2009-07-27       2009-07-30
    1602995       2009-07-27       2009-07-30
    1602995       2009-07-27       2009-07-30
    1602995       2009-07-27       2009-07-30
    1602995       2009-07-27       2009-07-30
    1602995       2009-07-27       2009-07-30
    1602995       2009-07-27       2009-07-30
    1602995       2009-07-27       2009-07-30
    1602995       2009-07-27       2009-07-30
    1602995       2009-07-27       2009-07-30
    1602995       2009-07-27       2009-07-30
    1602995       2009-07-27       2009-07-30
    1602995       2009-07-27       2009-07-30
    1602995       2009-07-27       2009-07-30
    1602995       2009-07-27       2009-07-30
```
Lots of identical intervals (2009-07-27, 2009-07-30) suggests the problem is caused by their non-deterministic ordering. Also notice that `2009-06-27`, the end date of the first interval, doesn't even appear in this list. Instead, we must have got it as the result of `dateadd(day, -30, '2009-07-27')`.

Here's what I think is happening. Let's take just 5 intervals from this list:
```
start_date  end_date
2009-06-16  2009-06-19
2009-07-01  2009-07-04
2009-07-27  2009-07-30
2009-07-27  2009-07-30
2009-07-27  2009-07-30
```

Then, `RAWDATA` subquery gives us:
```
event_date  event_type  start_ordinal
2009-06-16          -1              1
2009-07-01          -1              2
2009-07-27          -1              3
2009-07-27          -1              4
2009-07-27          -1              5
2009-07-19           1           NULL
2009-08-03           1           NULL
2009-08-29           1           NULL
2009-08-29           1           NULL
2009-08-29           1           NULL
```
In the next subquery, `MAX(start_ordinal)` and `ROW_NUMBER()` apply `ORDER BY event_date, event_type` to `RAWDATA`.
Now imagine that `MAX(start_ordinal)` orders `RAWDATA` as
```
event_date  event_type  start_ordinal
2009-06-16          -1              1
2009-07-01          -1              2
2009-07-19           1           NULL
2009-07-27          -1              3
2009-07-27          -1              4
2009-07-27          -1              5
2009-08-03           1           NULL
2009-08-29           1           NULL
2009-08-29           1           NULL
2009-08-29           1           NULL
```
while `ROW_NUMBER()` orders it as
```
event_date  event_type  start_ordinal
2009-06-16          -1              1
2009-07-01          -1              2
2009-07-19           1           NULL
2009-07-27          -1              4
2009-07-27          -1              5
2009-07-27          -1              3
2009-08-03           1           NULL
2009-08-29           1           NULL
2009-08-29           1           NULL
2009-08-29           1           NULL
```

Then, after calculating `MAX(start_ordinal) AS start_ordinal` and `ROW_NUMBER() AS overall_ord`, we get
```
event_date  event_type  start_ordinal  overall_ord
2009-06-16          -1              1            1
2009-07-01          -1              2            2
2009-07-19           1              2            3
2009-07-27          -1              4            4
2009-07-27          -1              5            5
2009-07-27          -1              3            6
2009-08-03           1              5            7
2009-08-29           1              5            8
2009-08-29           1              5            9
2009-08-29           1              5           10
```

Now we got two rows that satisfy the condition `(2 * e.start_ordinal) - e.overall_ord = 0`:
```
event_date  event_type  start_ordinal  overall_ord
2009-07-27          -1              3            6
2009-08-29           1              5           10
```

After applying this condition and recalculating `end_date`, we get `cteEndDates`
```
end_date
2009-06-27
2009-07-30
```

The rest is simple. The `cteEnds` gives us
```
start_date  end_date
2009-06-16  2009-06-27
2009-07-01  2009-07-30
2009-07-27  2009-07-30
```
and the `#final_cohort`
```
start_date  end_date
2009-06-16  2009-06-27
2009-07-01  2009-07-30
```

**Comment by chrisknoll** [comment]
Very good.  Ok, so either we just use start_ordinal as you suggest, or maybe I create a separate row_number() for the inner query to act as the tiebreaker.  Let me try some thigns and I'll propose a PR for this.

Very excellent detective work, you have fully digested the logic behind the era-building logic.

**Comment by chrisknoll** [comment]
I've raised a PR that will merge [this branch](https://github.com/OHDSI/circe-be/tree/deterministic-queries) so if you'd like to pull it down and run your test cases with it (the PR includes a test case to replicate what you did here), please give it a try.

If there are no objections, I'll merge this in the coming days.
