### ISSUE TITLE
Allow for event end dates

### ISSUE THREAD

**Issue by alondhe** [OHDSI/circe-be#168]
As @pbr6cornell outlined here: https://forums.ohdsi.org/t/limitations-of-atlas-cohort-definitions-tool/15752/2, we often need to anchor upon the end of an event. For instance, hospital discharge (visit_end_date) might be a useful index date.

**Comment by chrisknoll** [comment]
This feature is coming in next release of Circe.  Will allow you to modify the event date by using an offset from the start/end dates.  So, in the above example, you could modify the event dates to be end_date + 0d and end_date + 1d.

**Comment by chrisknoll** [comment]
Fixed in https://github.com/OHDSI/circe-be/pull/183.
