### ISSUE TITLE
performance of CTEs on mpp platforms

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/circe-be#172]
In working with AWS technical support they have identified an issue with how some CTEs are used in the generated SQL.  We have identified some potential approaches to improve performance and will create a branch for review once all their findings are available. In one particular finding the use of a CTE is preventing queries from completing in cases where there are very large (billions) record counts in tables that are used in multiple joins.

**Comment by schuemie** [comment]
I've also experienced issues with the CTEs in terms of performance, in this case at a partner site running **SQL Server**. I actually wrote code that automatically translates all CTEs to temp tables in all Circe-generated SQL. (In a private repo, can share if anyone's interested) that allowed this partner to complete execution of our study code.

**Comment by fdefalco** [comment]
Using temp tables instead of CTE seems like a viable solution based on what we're seeing.  The issues we have identified with redshift are 
- query planner struggles to properly account for a CTE because they inherently don't have statistics
- each reference of a CTE cause a complete re-evaluation of the CTE
- CTE reside in memory and can be too large for some platforms
- CTE do not take advantage of a distribution hash so the result of its evaluation is copied to all nodes in a cluster

A change of primary_events as a CTE to #primary_events as a temp table with a distribution key on person_id reduced overall runtime by 75% on some of the more problematic queries.

**Comment by schuemie** [comment]
That makes sense. I assume it is a similar story for SQL Server (except it won't have a distribution hash).

Somewhat related, as discussed [here](https://forums.ohdsi.org/t/optimizing-postgresql-server-for-ohdsi/14936/9) I've found that on Postgres, calling `ANALYZE` on the CodeSets temp table can make a huge difference.
