### ISSUE TITLE
Replace javascript semver with pure-Java implementation

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/circe-be#188]
Currently, the codebase depends on a JavaScript runtime engine that is embedded in Java in order to invoke semver expressions that are compatible with javascript libraries.  Since this was introduced in 2018, there has been progress making npm-based semver expressions supported in a pure Java library.

The issue with the current implementation is the dependency on a JavaScript engine leads to a 50MB dependency that excludes us from being included in certain repository environments (ie: CRAN).   

There is a library that I would like to investigate: [semver4j](https://github.com/semver4j/semver4j). 

This issue is to track the change to remove the JavaScript implementation of semver checks and replace it with a pure Java impl.

**Comment by RowanErasmus** [comment]
@chrisknoll I'll pick this up if you have not already begun

**Comment by RowanErasmus** [comment]
I'm working on it now, could not find something right out of the box, but am piecing together some functions from sever4j to make it work...

Guava was just required for the single method I replaced with one line...

**Comment by chrisknoll** [comment]
Ok, for context (if this helps) the purpose of this code is to yield a CDM version for a given asset (for example, cohort expression) and *during serialization* the function is called and it assigns the [appropriate CDM version to the object](https://github.com/OHDSI/circe-be/blob/90f8778c8b84ff87d1862707ddd9bae6d72c221d/src/main/java/org/ohdsi/circe/cohortdefinition/CohortExpression.java#L40).

The CdmVersion is a custom annotation used to specify the CDM version that is allowed (you can the use at the [CohortExpression ](https://github.com/OHDSI/circe-be/blob/90f8778c8b84ff87d1862707ddd9bae6d72c221d/src/main/java/org/ohdsi/circe/cohortdefinition/CohortExpression.java#L40)and criteria [attribute ](https://github.com/OHDSI/circe-be/blob/90f8778c8b84ff87d1862707ddd9bae6d72c221d/src/main/java/org/ohdsi/circe/cohortdefinition/LocationRegion.java#L9)level).

This is all handled in the [StandardUtils](https://github.com/OHDSI/StandardizedAnalysisUtils) repo in the [CdmVersionUtils ](https://github.com/OHDSI/StandardizedAnalysisUtils/blob/master/src/main/java/org/ohdsi/analysis/versioning/CdmVersionUtils.java) class.

I think the central class to needing this guava (or is it [gral](https://github.com/OHDSI/StandardizedAnalysisUtils/blob/68919ec4b7962310e01bb69feb79f89b3526e9fd/src/main/java/org/ohdsi/analysis/versioning/SemverUtils.java#LL4C1-L4C37)??)  runtime is in the SemverUtils function [getRangeIntersection](https://github.com/OHDSI/StandardizedAnalysisUtils/blob/68919ec4b7962310e01bb69feb79f89b3526e9fd/src/main/java/org/ohdsi/analysis/versioning/SemverUtils.java#L19).  If this can be changed from using a jsContext to invoke a javascript function and instead jsut use the pure-java impl, then I think that would get rid of it.

So, I may be confusing guava with GralVM so, sorry about that, but this issue is about removing gralvm and the implementation in SemverUtils with a pure java impl.

For reference, this is the [javascript](https://github.com/OHDSI/StandardizedAnalysisUtils/blob/master/src/main/resources/semver/semver-intersect.js) that performs the semver-intersect work that is used to determine the semver intersection logic.  So there's more to the work than just replacing a semver javascript implementation with a prue java one, but also taking the 'semver intersection logic' from the javascript implementation and changing it into a pure-java one.


-Chris

**Comment by RowanErasmus** [comment]
Thanks for the details, its the Graal stuf indeed required for the js.

The only question I have is to confirm wether or not the ohdsi cdmvalue only uses these >=, = kind of annotation and not this ~ ^ stuff from npm?

Rowan

**Comment by chrisknoll** [comment]
I believe we only use the >, >= to indicate that the supported version is at least a value (like >= 5.0 or >= 5.4.   I think we will need to support a range that is <= because eventually we get to things that are no longer supported in 6.0 so we will say something like range= `>=5.4 && < 6.0`.   Something like that. I do not believe we would say something like ^5.2....

I think the idea was that you have your root object like cohort expression that says >=5.0   From this starting point we get a range (maybe the starting point is actually `*` and from there we set up a lower and upper bound for the range.  Then we scan through the object elemetns looking for CdmVersion annotatins, and we 'shrink' the valid cdm range.  

Example: '* + >=5.0 becomes >= 5.0, then if you find >=5.3 later, it becomes >= 5.3...and later if we see < 6.0, the final range will be >= 5.3 && < 6.0 (in other words valued range is between 5.3 and up to but not including 6.0).   Maybe if we found things like ^5.2, those things get put into the range expression like >= 5.3 && < 6.0 && ^5.2.

The point of yielding this cdm version range is that once we have this cdm version range expression (ie: >= 5.3 && < 6.0 && ^5.2), we can then check to see if a given CDM version is compatable with the semver expression:

isCompatable("5.7", ">= 5.3 && < 6.0 && ^5.2") => true
isCompatable("6.1", ">= 5.3 && < 6.0 && ^5.2") => false
isCompatable("5.2", ">= 5.3 && < 6.0 && ^5.2") => false

We don't have a use of isCompatable yet but the idea is that when we support multiple CDM versions in circe, we can check if a target Source (which has a specific version) is compatible with the expression semver spec  In the above example, the first param is the CDM version of the source, and the second param is the CdmVersion range from the java object (from [determineCdmCompatibility](https://github.com/OHDSI/StandardizedAnalysisUtils/blob/68919ec4b7962310e01bb69feb79f89b3526e9fd/src/main/java/org/ohdsi/analysis/versioning/SemverUtils.java#L19).

Note that the `determineCdmCompatibility()` function is that you call the function and has a side effect: the input param (the CdmCompatibilitySpec ) has its `setCdmVersionRange()` on it after the version range is determined inside the function.  It feels a little confusing to me but I think they wanted to have this function as a `void()` signature.   

But I think that covers the extent of the functionality:   `determineCdmCompatability` establishes the semver range expression based on the elements (found by traversing the [object graph](https://github.com/OHDSI/StandardizedAnalysisUtils/blob/68919ec4b7962310e01bb69feb79f89b3526e9fd/src/main/java/org/ohdsi/analysis/versioning/CdmVersionUtils.java#L46)).  If there is a conflict for some reason (like the object resolves to requiring <6.0 && >= 6.1) it will throw an [exception](https://github.com/OHDSI/StandardizedAnalysisUtils/blob/68919ec4b7962310e01bb69feb79f89b3526e9fd/src/main/java/org/ohdsi/analysis/versioning/CdmVersionUtils.java#L35).

**Comment by RowanErasmus** [comment]
I've had a first crack at it https://github.com/OHDSI/StandardizedAnalysisUtils/pull/7

The && symbol is not part of the node semver syntax (which was the original implementation) it has ranges like this 3.4 - 5 in stead, but the idea stays the same :-)

**Comment by RowanErasmus** [comment]
Yes you are right, I did not bother with taking care of the 'or' which is a || I think, and it would be 5.0 - 5.2 || 5.4 - 6.0 so you get everything between 5.0 and 6.0 except 5.3. If you pass that now it throws an exception I can give it a go I guess, adding a couple of lines of extra insanity never hurt anyone.

**Comment by chrisknoll** [comment]
Fixed in fa4391bc4bb5899d7ba4a2a2bdc133d2fa856404.
