### ISSUE TITLE
"," as default decimal

### ISSUE THREAD

**Issue by catalamarti** [OHDSI/circe-be#193]
I don't know if this error has been already reported, but just in case.
I have created this cohort definition: https://atlas-demo.ohdsi.org/#/cohortdefinition/1782797/definition. This cohort could be instantiated correctly using the sql obtained from:
```r
cohortExpression <- CirceR::cohortExpressionFromJson(expressionJson = cohortJson)
cohortSql <- CirceR::buildCohortQuery(
  expression = cohortExpression, 
  options = CirceR::createGenerateOptions(generateStats = TRUE)
)
```
I asked a colleague to instantiate it and he has the following error:
![image](https://user-images.githubusercontent.com/18575244/236672593-7a57257f-1db0-45ee-bb01-f41a0863b0bb.png)
I have checked and my sql for this line of code it has `40.0000` instead of the `40,0000` I guess that this `,` is what bothers the sql and makes it crash. We changed manually the sql and it worked. I guess that he has the default decimal separator as "," instead of ".". 
Is there a way to solve this in `buildCohortQuery()` as it is easier than having to change the sql manually every time that there are decimals involved?

**Comment by chrisknoll** [comment]
I transfered this to circe-be because that is where the fix is needed.

**Comment by RowanErasmus** [comment]
It appears that this issue was already fixed here https://github.com/OHDSI/circe-be/commit/d765be362c77e019a1b501f8a7924868900d7dbd and that the change has been propagated. 

I searched through the code a bit to look for places that might had been missed but could not find any...

@catalamarti was your colleague using a recent (1.2.1+) version of CirceR?

**Comment by catalamarti** [comment]
I see, it could be the case.
Unfortunately we can not check what package version was he using at that moment. We will try again with the newest version.
Thanks!
