### ISSUE TITLE
Impala issue with distinct on group by queries

### ISSUE THREAD

**Issue by wivern** [OHDSI/circe-be#20]
Impala doesn`t support distinct with `group by` queries, 
moreover using **distinct** seems redundant with such kind of queries.
Example from src/main/resources/resources/cohortdefinition/sql/eraConstructor.sql:

````sql
select distinct @eraGroup , min(b.start_date) as start_date, b.end_date
	from
		(select distinct @eraGroup, groupid from cteSource) as a
	inner join
		cteEnds as b
	on a.groupid = b.groupid
	group by @eraGroup, end_date
```

**Comment by chrisknoll** [comment]
Can you confirm this is an issue with the current release of circe?  We rewrote those era queries to not use @eraGroup.

**Comment by wivern** [comment]
Oh, sorry. I`ve tested with 1.3.1 release and this error has gone. 
So issue can be closed.
