### ISSUE TITLE
Path typo in ConceptSetDbTest.java

### ISSUE THREAD

**Issue by jpetucci** [OHDSI/circe-be#207]
I had to correct the following typo in [ConceptSetDbTest.java](https://github.com/OHDSI/circe-be/blob/a032f64bb06be62e365e7249b1ed98d0abb6f111/src/test/java/org/ohdsi/circe/conceptset/ConceptSetDbTest.java#L91C10-L91C11) to get the Maven compilation to complete.

````
final String[] testDataSetsVerify = new String[] {"/conceptSet/inClause_VERIFY.json"};
````
to

````
final String[] testDataSetsVerify = new String[] {"/conceptset/inClause_VERIFY.json"};
````

**Comment by chrisknoll** [comment]
Ah, it's a case-sensitivity problem, since this works on Windows.   It's helpful if you point out where the typo lies, but we can see about pushing a fix.
