### ISSUE TITLE
Cohort definitions group criteria combination shows unexpected behaviour (with Oracle) 

### ISSUE THREAD

**Issue by thisismexp** [OHDSI/circe-be#209]
The following problem occurs when defining cohort definitions with nested criteria having only one criterion in a group.

### Expected behavior
Selecting **any** vs. **all** in the "having any/all of the following criteria" should not affect the generated cohort if only one sub-criterion is used within that criteria group:
![Screenshot from 2024-05-22 11-54-34](https://github.com/OHDSI/Atlas/assets/19307322/3f2d133e-1c59-4a85-b59b-0c7f3c73c26d)

### Actual behavior
In our example, selecting **all** generates a cohort with 3 people included, whereas selecting **any** leads to 940 persons being included. This problem also affects groups in inclusion criteria definitions.

### Steps to reproduce behavior
We use Oracle 19c as DBMS (the issue seems not be present with other dialects, at least not with Postgres), find a exemplary cohort definition attached ([test_cohort_definition.json](https://github.com/OHDSI/Atlas/files/15402457/test_cohort_definition.json)).

### Further information
The only difference in the generated SQL statements is the following:
![Screenshot from 2024-05-22 11-52-35](https://github.com/OHDSI/Atlas/assets/19307322/827b7da8-1bb3-466f-bfd4-525e0cfa16f9)

If this is an issue of WebAPI, pls feel free to close this one and I will go ahead and open another one in the WebAPI repo.

Thanks for your help :)

**Comment by thisismexp** [comment]
We discovered our mistake and I will go ahead and close this issue, sry for opening it in the first place.

We had issues with our OBSERVATION_PERIOD entries (duplicates, overlapping ones) that, due to the contained JOIN operation on OBSERVATION_PERIOD, let to the unexpected number of matched expressions. Although this should be prevented by the CDM definition itself, using count(DISTINCT index_id) would prevent this from happening at all and might be useful to include.

Thank you so much for your help, your comment ultimately pointed me to our issue.

**Comment by chrisknoll** [comment]
> Although this should be prevented by the CDM definition itself, using count(DISTINCT index_id) would prevent this from happening at all and might be useful to include.

But then you wouldn't have discovered the OP issue you had and other analyses would break because of it.  So we'll leave it as is and leave this as a cautionary tale to follow the CDM specs.
