### ISSUE TITLE
Impala fails with null_type in column visit_occurrence_id

### ISSUE THREAD

**Issue by wivern** [OHDSI/circe-be#23]
When running cohort generation over Impala got following exception:

java.sql.SQLException: [Simba][ImpalaJDBCDriver](500051) ERROR processing query/statement. Error Code: 0, SQL state: TStatus(statusCode:ERROR_STATUS, sqlState:HY000, errorMessage:AnalysisException: Unsupported type 'null_type' in column 'visit_occurrence_id' of table 'a9brxc8bqualified_events'

**Comment by chrisknoll** [comment]
To do visit-linking between events, we exposed a visit_occurrence_id, but some domain objects don't actually link to a visit_occurrenc_id, so to have those kind of events match the row format for the others, we just expose a 'null' value as the visit_occurrence_id.

**Comment by wivern** [comment]
Thank you for explanation, it`s clear.
But Impala doesn't support automatic type casting and when it meet `null` instead of value it crashes with error above. So my suggestion is to add explicit type cast for visit_occurrence_id which is unnecessary for other DBMS but is critical for Impala.
My pull request #22 contains this changes.

**Comment by chrisknoll** [comment]
Ok, we'll get #22 merged in.
