### ISSUE TITLE
Cohort constructor - option to fix date of entry and exit

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/circe-be#26]
For financial reporting and analytics, we need to have a cohort with fixed date of entry and exit. E.g. if we are analyzing the total cost of care for the calendar year 2017, then the cohort start date may no be before January 1st 2017, and cohort end date may not be after December 31st 2017. However, subject's may enter the cohort at any time and exit at any time during 2017. 

If a subject enters the cohort before 2017, then the cohort start date is changed to '2017-01-01'; if a subject exits the cohort after 2017, then the cohort end date is changed to '2017-12-31'

Example: If current cohort constructor outputs the following

Subject_ID | Cohort_start_date | Cohort_end_date
-- | -- | --
1 | 1-Mar-16 | 31-Aug-16
1 | 15-Dec-16 | 15-Mar-17
1 | 1-Apr-17 | 30-Sep-17
1 | 1-Nov-17 | 28-Feb-18

We need an option to convert this to

Subject_ID | Cohort_start_date | Cohort_end_date
-- | -- | --
1 | 1-Jan-17 | 15-Mar-17
1 | 1-Apr-17 | 30-Sep-17
1 | 1-Nov-17 | 31-Dec-17

@gklebanov @pavgra

**Comment by gowthamrao** [comment]
@cgreich i have tried a few options, and have failed. Do you have an example that works.

Also (you probably guessed) - we are trying to build cohorts based on payer plan period table. The use case is, who are the people who had atleast one day of coverage by the payer in 2017. Limit exposure to 2017 only, i.e. exposures/events/observations before 2017 are baseline characteristics.

**Comment by gowthamrao** [comment]
@cgreich  i tried your suggestion here 

http://www.ohdsi.org/web/atlas/#/cohortdefinition/1718674

![image](https://user-images.githubusercontent.com/13936600/35484293-0f116bb0-041c-11e8-9b4a-f48dabd7739f.png)

That will at best build this

Subject_ID | Cohort_start_date | Cohort_end_date
-- | -- | --
1 | 15-Dec-16 | 15-Mar-17
1 | 1-Apr-17 | 30-Sep-17
1 | 1-Nov-17 | 28-Feb-18


But not this

Subject_ID | Cohort_start_date | Cohort_end_date
-- | -- | --
1 | 1-Jan-17 | 15-Mar-17
1 | 1-Apr-17 | 30-Sep-17
1 | 1-Nov-17 | 31-Dec-17

**Comment by cgreich** [comment]
@gowthamrao: Could create one for you.

**Comment by cgreich** [comment]
@gowthamrao: You could pick the observation period overlapping with your year, and then limit the dates to Jan to Dec. What do you want your dates be:
- The actual observation period dates overlapping with 2017
- The actual drug era or condition era dates in 2017
- Jan and Dec
?

**Comment by gowthamrao** [comment]
I think that's what I did here 
https://github.com/OHDSI/circe-be/issues/26#issuecomment-361074288


Cohort Start date should be max(start_date, '2017-01-01')
Cohort end date should be min(end_date, '2017-12-31')

**Comment by gowthamrao** [comment]
The solution, I think is the following: @chrisknoll  

If fixed date censor is selected then we will apply this after the collapse strategy as follows

```
CREATE TEMP TABLE fixed_date_censor as
with fixed_date as
(
select person_id, case when start_date < @left_fixed_date then @left_fixed_date else start_date end as start_date, case when end_date > @right_fixed_date then @right_fixed_date else end_date end as end_date
from FROM collapse_constructor_output CO
)
select person_id, start_date, end_date
from fixed_date
where start_date <= end_date;
```

Then use that new temporary table in the insert 
```
DELETE FROM @target_database_schema.@target_cohort_table where cohort_definition_id = @target_cohort_id;
INSERT INTO @target_database_schema.@target_cohort_table (cohort_definition_id, subject_id, cohort_start_date, cohort_end_date)
select @target_cohort_id as cohort_definition_id, person_id, start_date, end_date
FROM fixed_date_censor FD
;
```

**Comment by chrisknoll** [comment]
A few things going on here I just want to square away before talking about potential solution:

In the ObservationPeriod criteria that @cgreich mentioned, you can use the 'specify start and end dates' so override the OP's start and end date. However, this does 2 things:

- The start and end date of the 'event' selected will be assigned the user-specified dates, which will be used to find all the correlated events relative to the user-specified start date (if those extra criteria are specified
- Only people who have observation periods that completely cover the user-specified dates will be found.  So if someone starts an OP of 4/1/2017 - 9/1/2017, and the user specified dates are 1/1/2017 - 1/1/2018, this person wont' be found.

So, I do not think observation period criteria applies here.  With respect to the fixed date censor, I think that will work, and it should probably work independently of any of the other exit strategies (date offset or persistent exposure), or collapsing (as @gowthamrao mentioned, all this happens after the collapse).

Since this is an optional thing, we can add an option in the cohort expression to specify a 'study window', and if specified  we do the max(cohort_start, user_start_date) and min(cohort_end_date, user_end_date) and put that logic into the INSERT INTO statement (or we can create another temp table like @gowthamrao describes).

One thing I will say about this idea:  normally we try not to define cohort definitions that are study-specific if it's not necessary.  @gowthamrao : if you have a cohort of people with various start-end dates that might fall outside of your study window, why isn't the cohort being trimmed at analysis time for your study window instead of making a study-specific cohort?

Example of my point:  If you want to do an analysis on a cohort X for periods Q1-Q4 for 2016 and 2017, you'd have to define 8 cohorts with each of these windows specified....vs just splitting the single cohort X into those groups by finding the people that overlap each of the windows, and re-assigning their start-ends to be restricted to the desired window, and drop those people that aren't in the window at all.

So, technically the feature is possible, but in practice, I'm not sure why you wouldn't handle cutting up the cohort by time windows externally from the cohort definition.

**Comment by gowthamrao** [comment]
@chrisknoll  you are correct

> Only people who have observation periods that completely cover the user-specified dates will be found. So if someone starts an OP of 4/1/2017 - 9/1/2017, and the user specified dates are 1/1/2017 - 1/1/2018, this person wont' be found.

The observation period criteria does not apply here. Here is why

![image](https://user-images.githubusercontent.com/13936600/35486677-8ffad3a6-043f-11e8-9abe-7f44075b2373.png)



Because -- 
```
WHERE C.OBSERVATION_PERIOD_START_DATE <= CAST('2009-01-01' as Date) and C.OBSERVATION_PERIOD_END_DATE >= CAST('2009-01-01' as Date)
AND C.OBSERVATION_PERIOD_START_DATE <= CAST('2009-12-31' as Date) and C.OBSERVATION_PERIOD_END_DATE >= CAST('2009-12-31' as Date)
```
is equal to

WHERE C.OBSERVATION_PERIOD_START_DATE <= CAST('2009-01-01' as Date) and ~~C.OBSERVATION_PERIOD_END_DATE >= CAST('2009-01-01' as Date)~~
~~AND C.OBSERVATION_PERIOD_START_DATE <= CAST('2009-12-31' as Date) and~~ C.OBSERVATION_PERIOD_END_DATE >= CAST('2009-12-31' as Date)

In this case, 

Subject_ID | Cohort_start_date | Cohort_end_date
-- | -- | --
1 | 1-Apr-09 | 30-Sep-09

would not be used.  


If we really have to use the 'specify period' option then we will have to do something complex like (not very confident about this solution) to get the periods that started before '2009-12-31' and observation periods that ended after '2009-01-01'

Like this (I think)
```
  -- Begin Observation Period Criteria
select C.person_id, C.observation_period_id as event_id
           , case when start_date < CAST('2009-01-01' as Date) then CAST('2009-01-01' as Date) else start_date end as start_date
         , case when end_date > CAST('2009-12-31' as Date) then CAST('2009-12-31' as Date) else end_date end as end_date
         , C.period_type_concept_id as TARGET_CONCEPT_ID
        , NULL as visit_occurrence_id
from 
(
        select op.*, row_number() over (PARTITION BY op.person_id ORDER BY op.observation_period_start_date) as ordinal
        FROM @cdm_database_schema.OBSERVATION_PERIOD op
) C

WHERE C.OBSERVATION_PERIOD_START_DATE <= CAST('2009-12-31' as Date) and C.OBSERVATION_PERIOD_END_DATE >= CAST('2009-01-01' as Date) and
(case when start_date < CAST('2009-01-01' as Date) then CAST('2009-01-01' as Date) else start_date end) > (case when end_date > CAST('2009-12-31' as Date) then CAST('2009-12-31' as Date) else end_date end)


-- End Observation Period Criteria

```

I dont think this approach is good

**Comment by gowthamrao** [comment]
@chrisknoll  i really like specifying study window.

> specify a 'study window', and if specified we do the max(cohort_start, user_start_date) and min(cohort_end_date, user_end_date) and put that logic into the INSERT INTO statement (or we can create another temp table like @gowthamrao describes).

To answer

> why isn't the cohort being trimmed at analysis time for your study window instead of making a study-specific cohort?

> Example of my point: If you want to do an analysis on a cohort X for periods Q1-Q4 for 2016 and 2017, you'd have to define 8 cohorts with each of these windows specified....vs just splitting the single cohort X into those groups by finding the people that overlap each of the windows, and re-assigning their start-ends to be restricted to the desired window, and drop those people that aren't in the window at all.

Absolutely possible, but it is a trade off between either doing it insider or outside. Doing it outside, is more 'advanced' and temporal functionality of feature extraction may make it easier -- but it makes using standard Atlas functions like attrition diagram, Heracles reports, Incidence rate, or PLP etc. Difficult and out of reach of standard user.

So - i think adding 'study window' as an optional is a fantastic idea!

**Comment by chrisknoll** [comment]
Ok, we're in vigorous agreement that altering observation period criteria isn't a solution here.  We can go with an optional 'study window' setting that , if specified, does left- and right-trim of cohort start and ends such that they fall inside the study window, while also dropping those people that have no overlap with the study window.

**Comment by cgreich** [comment]
@gowthamrao, @chrisknoll:

We need to find a way to make these clear in the UI. Because nobody is going to read this pamphlet here or, less so, understand it. I don't have a good idea, other than playing with the text on the screen.

**Comment by chrisknoll** [comment]
Agreed @cgreich , tho that will be an issue tracked under Atlas (as that contains the UI code for the expresison editor (for now)).  We'll track the back-end and data-model changes as part of this issue.

**Comment by gowthamrao** [comment]
Instead of calling 'study window', lets call it 'censor window'. Here is my rationale: a cohort is built mostly to study its characteristics. But, a cohort maybe built to intervene (e.g. a care management entity may be building cohorts that are eligible for an intervention campaign). So, calling this new function 'study window' may miss the idea of building cohorts for 'intervention' purposes. If there is no objection, we should call it 'censor window'.

Another point I think we should be clear about is -- censor's may happen on left, or right or both. The example above is censor at both left and right e.g. 2017-01-01 and 2017-12-31. However, we may want left only which is starting 2017-01-01 and ending anytime. Or, right now which is starting anytime but ending 2017-12-31.

@gklebanov @pavgra this thought just came to my mind - i.e. left, right or both censor.

**Comment by chrisknoll** [comment]
I think the model will have a start and end date in the window, and if either of them are empty, that means you leave it open ont he side (startDate = left sensor, endDate = right censor, both dates = both censor). We can ignore the whole thing if both are blank, but possibly put a UI warning that they asked for censoring but didn't provide any values.

**Comment by pavgra** [comment]
@gowthamrao, @chrisknoll, I am going to start working on the feature tomorrow and, hopefully, will create a PR on the same day.

**Comment by chrisknoll** [comment]
Hi, @pavgra , that sounds good.  Some implementation notes:

The model change is in org.ohdsi.circe.cohortdefinition.CohortExpression.  We just need a new field of type org.ohdsi.circe.cohortdefinition.Period (the Period class contains fields to store startDate and endDate). I think @gowthamrao suggestion of calling this field 'CensorWindow' makes sense.

In org.ohdsi.circe.cohortdefinition.CohortExpressionQueryBuilder, we just need additional (optional) logic if CensorWindow != null:

- if CensorWindow. start date is != null, we need to remove those people who have chort_end_date < CensorWindow.startDate, and update anyone who has a start date < CensorWindow.startDate to be the CensorWindow.startDate.
- if CensorWindow.endDate != null, we need to remove people who have cohort_start_date > CensorWindow.endDate, and update anyone who has a end_date > CensorWindow.endDate to be the CensorWindow.endDate.

The above I think can be performed in 2 statements: 

- delete from #finalCohort where end_date < CensorWindow.startDate and start_date > CensorWindow.endDate
- update #finalCohort set start_date = {case statement to pick later of CensorWindow.startDate and start_date} , end_date = {case statement to pick earlier of CensorWindow and end_date}

Note: CensorWindow.startDate or CensorWindow.endDate could either be null, so you only want to delete people/update dates if the start/end is an actual value.
