### ISSUE TITLE
CAST for visit_occurrence fails

### ISSUE THREAD

**Issue by pavgra** [OHDSI/circe-be#31]
Unfortunately, the [PR](https://github.com/OHDSI/circe-be/pull/22), which was fixing Impala support, has broken Postgres. We've faced such case, where among `Initial cohort events` there is `Condition Era Criteria`, which produces following line of code in resulting cohort SQL:
```
...
select C.person_id, C.condition_era_id as event_id, C.condition_era_start_date as start_date, C.condition_era_end_date as end_date, C.CONDITION_CONCEPT_ID as TARGET_CONCEPT_ID, NULL as visit_occurrence_id
...
```

From a big picture perspective, it equals to:
```
select cast(visit_occurrence_id as bigint)
FROM (
	select NULL as visit_occurrence_id
) P
```

Which causes troubles for Postgres to derive variable type (here is a [link](https://stackoverflow.com/questions/18073901/failed-to-find-conversion-function-from-unknown-to-text) regarding the topic) and it crashes with following exception:
```
ERROR: failed to find conversion function from unknown to bigint
```

Currently, we are looking for solution, but wanted to pop up the problem for others to be informed.

**Comment by chrisknoll** [comment]
What if we change it to this:

```
select C.person_id, C.condition_era_id as event_id, C.condition_era_start_date as start_date, C.condition_era_end_date as end_date, C.CONDITION_CONCEPT_ID as TARGET_CONCEPT_ID, CAST(NULL as bigint) as visit_occurrence_id
```

**Comment by chrisknoll** [comment]
I did a search, and there's a few places where we do NULL as visit_occurrence_id:
https://github.com/OHDSI/circe-be/search?utf8=%E2%9C%93&q=NULL+as+visit_occurrence_id&type=

What's odd is that the outer queries to these select NULL does cast the column back to a bigint.  But, if we need it done directly from the initiating select statement, then we should go through each of those query fragments (conditionEra, drugEra, doseEra, etc) and cast the NULL to bigint directly.
