### ISSUE TITLE
Cohort exit criteria based on qualified event date

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/circe-be#34]
We want to build a cohort, where the cohort_start_date and cohort_end_date are spans of time when qualified-events (initial event cohort) are TRUE and Additional Qualifying criteria are true.

But, 
> By default, cohort exit at the event's op end date

Is there a way to use qualified event end date as the cohort exit date?

**Comment by chrisknoll** [comment]
Yes, use the date offset exit strategy, and specify that the cohort exits 0 days after the event's end date.

**Comment by gowthamrao** [comment]
Thats it! Thank you Mr. Logic @chrisknoll

**Comment by chrisknoll** [comment]
Btw: also use your collapse gap option to link these events together into joined cohort periods.
