### ISSUE TITLE
Indiscriminate use of 'invalid_reason is null'

### ISSUE THREAD

**Issue by schuemie** [OHDSI/circe-be#35]
All concept sets implicitly apply the requirement `invalid_reason is null`. However, this is not always desired. For example, I'm looking at source concepts for zoledronic acid injections using these concept IDs: 2718650, 2720787, 2718649, 44786564, 44786608. Only one of those appears to be currently valid, but the others are used a lot in the data, likely at a time in history when they were valid (or even if Christian says they weren't I would like to detect them). Currently, I have no option to include these concepts other than to manually modify the SQL.

Desired behavior: ability to define criteria using source concepts that were valid at the time, even if they no longer are valid now.

Actual behavior: source concepts that are currently no longer valid are automatically discarded.

Solution: Not sure. The whole reasoning for when a concept is valid or invalid is unclear to me. For source concepts the current behavior is definitely wrong, since the codes were valid in the past, and so at the very least the `invalid_reason is null` statement should be replaced with one testing whether the occurrence date is within the valid period. I would like to have the check for valid concepts disabled in this example altogether. I think these concerns might extend to standard concepts as well.

**Comment by gowthamrao** [comment]
Lot of discussion about this here

http://forums.ohdsi.org/t/proposal-to-keep-outdated-standard-concepts-active-and-standard/3695

**Comment by dimshitc** [comment]
and here's the final decision
http://forums.ohdsi.org/t/proposal-to-keep-outdated-standard-concepts-active-and-standard/3695/22

**Comment by schuemie** [comment]
Thanks! In that case the `invalid_reason is null` statement would appropriately.

**Comment by chrisknoll** [comment]
Re-opening this per request from https://github.com/OHDSI/ETL-CDMBuilder/issues/49.  Will remove invalid_reason checks from concept set queries.
