### ISSUE TITLE
Generated SQL performance optimizations

### ISSUE THREAD

**Issue by pavgra** [OHDSI/circe-be#45]
## Separate query for primary events

**Background**
Today there is a single query for initial events which combines both primary_events (as CTE) and initial event inclusion criteria calculation. When the query is executed at Impala with disabled spill to disk, the CTE is placed into RAM and due to the typical results size (which e.g. in case of Truven are really big), it causes `memory limit exceeded` quite often.

**Suggestion**
Split initial event calculation into two steps with a temp table for each: primary events calculation and application of inclusion criteria for primary events.

## Duplicated row_number calculation in primary events

**Background**
`row_number` is calculated both in inner query of primary events (`row_number() OVER (PARTITION BY E.person_id ORDER BY E.start_date ASC) ordinal` in `E` subquery) and at top-level select of primary events (`row_number() over (PARTITION BY P.person_id order by P.start_date) as event_id`).

**Suggestion**
The latter row_number calculation could be replaced with results of `ordinal` for `Limit initial events to: all events` case and with `1` for `Limit intiial events to: earliest / latest` case.

## Calculation of ordinal only if required

Was discovered as a part of the performance issues research. @chrisknoll logged as a separate issue https://github.com/OHDSI/circe-be/issues/44

## JOIN types

Was suggested by @chrisknoll during a discussion of the performance issues. Covered by https://github.com/OHDSI/circe-be/pull/42

**Comment by chrisknoll** [comment]
These optimizations have been incorporated in the 1.9 line of Circe.
