### ISSUE TITLE
Support for payer_plan_period.contract_concept_id

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/circe-be#50]
It would be desirable for Atlas and circe-be to support building cohorts using payer_plan_period.contract_concept_id, payer_plan_period.contract_source_concept_id. 

contract_concept_id and contract_source_concept_id were added by OMOP CDM vocabulary workgroup to the upcoming release of CDM 6.x, currently in [dev ](https://github.com/OHDSI/CommonDataModel/blob/Dev/PAYER_PLAN_PERIOD/PAYER_PLAN_PERIOD.md)branch of CDM.

**Comment by chrisknoll** [comment]
CDM v6 has been defunct. Will address this issue when it is re-introduced in a future CDM version.
