### ISSUE TITLE
String search criteria for some fields from Payer plan period table

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/circe-be#59]
The CDM and vocabulary workgroup has an ongoing effort to standardize the vocabulary concepts for use with payer plan period table. This is a major effort because of absence of good external vocabulary that may be adopted by the community. We are exploring various candidate options. 

Discussions [here ](https://github.com/OHDSI/CommonDataModel/issues/120)and [here](https://github.com/OHDSI/circe-be/issues/4)

One known limitation of standardizing concepts, is that the anticipated significant difference in how each administrative unit (e.g. US claims vs Eurpoean vs Korean claims systems) represents the constructs of a payer, plan (benefit design) or sponsor of benefit. While high level concepts (Medical vs dental) maybe standardized as OMOP vocabulary, low level concepts may never be.represented in OMOP vocabulary. Concepts are being vetted by the CDM and Vocabulary workgroup members right now, such as
![image](https://user-images.githubusercontent.com/13936600/46258029-13b99980-c492-11e8-9991-2b2a8e4de18e.png)

In this issue, I am requesting the addition of 'String search' in Atlas/circe-be to support the fields 
- payer_source_value
- plan_source_value
- sponsor_source_value
- contract_source_value 

The UI in Atlas may be like a drop down such as below
![image](https://user-images.githubusercontent.com/13936600/46258024-f4bb0780-c491-11e8-92fe-4f6521c45783.png)

There is precedence for this type of string search in Atlas - especially for drug_exposure and observation (see below)- because we cannot standardize using OMOP vocabulary concepts information such as LOT# of drug or Stop_reason
![image](https://user-images.githubusercontent.com/13936600/46258067-87f43d00-c492-11e8-960d-5e763674e8d2.png)

**Comment by chrisknoll** [comment]
This is a CDM V6 feature, which has been defunct.  We can re-open this issue if it comes into a 5.x feature, or if it is re-introduced in future versions.
