### ISSUE TITLE
Temp tables

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/circe-be#6]
Some of the temp tables are explicitly defined, others are implicitly defined.

Explicit definitions
```
create table #inclusionRuleCohorts 
(
  inclusion_rule_id bigint,
  person_id bigint,
  event_id bigint
)
;
```

Implicit definitions
```
create table #qualified_events
as
with primary_events (event_id, person_id, start_date, end_date, op_start_date, op_end_date) as
(
@primaryEventsQuery
)
SELECT event_id, person_id, start_date, end_date, op_start_date, op_end_date
INTO #qualified_events
FROM 
(
  select pe.event_id, pe.person_id, pe.start_date, pe.end_date, pe.op_start_date, pe.op_end_date, row_number() over (partition by pe.person_id order by pe.start_date @QualifiedEventSort) as ordinal
  FROM primary_events pe
  @additionalCriteriaQuery
) QE
@QualifiedLimitFilter
;
```

some DBMS don't support implicit definitions - is it reasonable to change the cohort-constructor to use explicit definitions?

**Comment by chrisknoll** [comment]
When it becomes a problem, we can try to address it, but the purpose of Create Table as Select is for optimal performance on various MPP systems (PDW and Redshift).  

Let's reopen this when we have a specific db dialect that is supported by sqlrender but doesn't support CTAS.
