### ISSUE TITLE
Support for Cost (CDM 6+) for Cohort definition (and cohort characterization)

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/circe-be#60]
It would be a great new functionality in Atlas if we build cohorts based on cost criteria. As an extension, cost criteria in circe-be may be usable as part of the new cohort characterization functionality in Atlas.

In health economic analysis it is common to build cohorts based on cost criteria. Example, we would like to build a cohort of individuals who experienced costs above a certain threshold. These cohorts may then be used in patient level predictions to predict high cost claimants.

We would like to build cohorts using a combination of cost_concept_id, cost_type_concept_id and currency_concept_id. In addition, they must 'joinable' to payer_plan_period, drug_exposure and visit_occurrence table as follows

```
left join cost.payer_plan_period_id = payer_plan_period.payer_plan_period_id
left join cost.cost_event_id = visit_occurrence.visit_occurrence_id
left join cost.cost_event_id = visit_detail.visit_detail_id
left join cost.cost_event_id = drug_exposure.drug_exposure_id
```

The joins will need to take into account [this ](https://github.com/OHDSI/CommonDataModel/issues/164) decision by CDM WG on switching domain_id to *_concept_id

**Use cases for cohort definition:**
- Inclusion criteria where the cost for the visit was greater then 20,000 USD
- Inclusion criteria where the cost for the drug was greater then 10,000 USD
- Initial events where the sum of cost for a person in a certain period, such as calendar year 2018, was between 100,000 USD and 200,000 USD 
- Visits where sponsor X (by joining to payer_plan_period) paid more than 25,000 USD for the person in the past 6 months prior to initial diagnosis of Diabetes Mellitus.

**Cohort characterization:**
As an extension, we can then use these to characterize any cohort and answer questions like - what %age of the persons in the cohort had a cost of > 25,000 during the cohort period.

**Comment by chrisknoll** [comment]
CDM6 seems to be defunct, so we'll close this out.
