### ISSUE TITLE
Allow events from outside observation period as Initial event

### ISSUE THREAD

**Issue by pavgra** [OHDSI/circe-be#78]
Use case: location as an initial event. Location's start/end dates won't be inside an observation period.

**Comment by pbr6cornell** [comment]
A cohort is defined as a set of persons satisfying one or more criteria for a duration of time.  That duration of time should belong within an observation period.   We should not allow for selection of any initial events that fall outside of observation period, as that breaks convention.   Location is not a valid initial event.  Rather, specifying a moment in time (such as observation period start date) and then evaluating location at that date, could be appropriate.

**Comment by chrisknoll** [comment]
Agreed.  As long as locations could be outside of an observation period, we can't determine cohort exit based on end of continuous observation, won't be able to determine prior continuous observation, etc.

The work around is to find some index event within an observation period, and then use additional criteria to determine if the location existed within a certain time window of the index event.
