### ISSUE TITLE
Wrong datatype in Codesets for Negative Controls

### ISSUE THREAD

**Issue by pavgra** [OHDSI/circe-be#88]
1. The [resources/cohortdefinition/negativecontrols/sql/codesetQuery.sql](https://github.com/OHDSI/circe-be/blob/master/src/main/resources/resources/cohortdefinition/negativecontrols/sql/codesetQuery.sql) defines `ancestor_concept_id` as `bigint`
2. Later, PLE analysis uses the `ancestor_concept_id` to populate `cohort_definition_id` which is integer

That causes datatype conversion issue in some databases:
```
Expression 's.cohort_definition_id' (type: BIGINT) would need to be cast to INT for column 'cohort_definition_id'
```

The proposed solution is to alter the `ancestor_concept_id` type to regular `integer` since it is populated with just `concept_id`-s:
```
INSERT INTO #Codesets (ancestor_concept_id, concept_id)
 SELECT ancestor_concept_id, descendant_concept_id
 FROM @cdm_database_schema.CONCEPT_ANCESTOR
 WHERE ancestor_concept_id IN (@outcome_ids)
;
```

**Comment by chrisknoll** [comment]
CocneptIDs are bigint, so we can't alter the ancestor_concept_id to int.
