### ISSUE TITLE
Reporting confusion between row_number() and dense_rank()

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/circe-be#9]
@gowthamrao ,

This is related to some of the recent work that changed the selecting 'earliest' and 'first' as using dense_rank() as the window function, allowing multiple events on the same day to be evaluated.

The problem stems from the 'inclusion report' statistics where prior to dense_rank(), the report was able to be viewed as a 'person-level' report because row_number() means that a single event would be returned per person.  Now that we use dense_rank(), we run into the case where if a person has 5 events of a type in the same day, the inclusion report appears like there were 5 people evaluated.   In the row_number() case, it would only use 1 event, and then the count in the report would be 1, which would correspond to a count of people.  @pbr6cornell  has concerns (as do I) about how this change means a breaking change with how the report numbers are interpreted.

This issue report is to discuss how we can think about how we specify the cohort definition in a way that we can talk in terms of 1 event per person so that our reporting can be more interpret-able.  Some ideas:

- use row_number() in the 'earliest per person/latest per person' but leave dense_rank() in the 'first occurrence in history,  
- Have a global cohort definition setting that will specify if we should use row_number() or dense_rank() (not sure how we would word this)
- Change up our reporting statistics so that it becomes something more person-centric

This isn't all the options, but things to think about.  I feel that we are going to need to come up with a solution for this quickly because the assumption that going to dense_rank() is going to have very large negative effects on the people that interpret the reports, and so we're going to want to address this prior to it's inclusion into next release of atlas.

**Comment by gowthamrao** [comment]
@chrisknoll obviously unforeseen problem. My initial thought is our approach should be as you described
> Change up our reporting statistics so that it becomes something more person-centric

Reason is that cohort-build process may evolve as we support more complex methods. Constraining it by assumptions of the reporting portion is probably not best.

That being said - we can do quite a bit, without sacrificing the new functionality we introduced (restrict to same visit_occurrence_id).

The temp tables that are used in the statistics calculations are #inclusionRuleCohorts, #qualified_events and #included_events. These tables should not have duplicate records. A quick solution is to put a DISTINCT in the insert statement 

eg. https://github.com/OHDSI/circe-be/blob/master/src/main/resources/resources/cohortdefinition/sql/inclusionrule.sql 
change from
```
INSERT INTO #inclusionRuleCohorts (inclusion_rule_id, person_id, event_id)
select @inclusion_rule_id as inclusion_rule_id, person_id, event_id
FROM 
(
  select pe.person_id, pe.event_id
  FROM #qualified_events pe
  @additionalCriteriaQuery
) Results
;
```

to
```
INSERT INTO #inclusionRuleCohorts (inclusion_rule_id, person_id, event_id)
select DISTINCT @inclusion_rule_id as inclusion_rule_id, person_id, event_id
FROM 
(
  select pe.person_id, pe.event_id
  FROM #qualified_events pe
  @additionalCriteriaQuery
) Results
;
```
addition of the 'distinct' will eliminate the problem from inclusionRuleCohorts

-----------------
#qualified_events will have duplicates, because it will carry forward `visit_occurrence_id`. We can't do anything about that during table's creation process, but we can during calculation time

```
with cteIncludedEvents(event_id, person_id, start_date, end_date, op_start_date, op_end_date, ordinal) as
(
  SELECT event_id, person_id, start_date, end_date, op_start_date, op_end_date, dense_rank() over (partition by person_id order by start_date @IncludedEventSort) as ordinal
  from
  (
    select Q.event_id, Q.person_id, Q.start_date, Q.end_date, Q.op_start_date, Q.op_end_date, SUM(coalesce(POWER(cast(2 as bigint), I.inclusion_rule_id), 0)) as inclusion_rule_mask
    from #qualified_events Q
    LEFT JOIN #inclusionRuleCohorts I on I.person_id = Q.person_id and I.event_id = Q.event_id
    GROUP BY Q.event_id, Q.person_id, Q.start_date, Q.end_date, Q.op_start_date, Q.op_end_date
  ) MG -- matching groups
{@ruleTotal != 0}?{
  -- the matching group with all bits set ( POWER(2,# of inclusion rules) - 1 = inclusion_rule_mask
  WHERE (MG.inclusion_rule_mask = POWER(cast(2 as bigint),@ruleTotal)-1)
}
)
select event_id, person_id, start_date, end_date, op_start_date, op_end_date
into #included_events
FROM cteIncludedEvents Results
@ResultLimitFilter
;
```
change to

```
with cteIncludedEvents(event_id, person_id, start_date, end_date, op_start_date, op_end_date, ordinal) as
(
  SELECT event_id, person_id, start_date, end_date, op_start_date, op_end_date, dense_rank() over (partition by person_id order by start_date @IncludedEventSort) as ordinal
  from
  (
    select Q.event_id, Q.person_id, Q.start_date, Q.end_date, Q.op_start_date, Q.op_end_date, SUM(coalesce(POWER(cast(2 as bigint), I.inclusion_rule_id), 0)) as inclusion_rule_mask
    from 
   (select distinct q.event_id, q.person_id, q.start_date, q.end_date, q.op_start_date, q.op_end_date from #qualified_events q) Q
    LEFT JOIN #inclusionRuleCohorts I on I.person_id = Q.person_id and I.event_id = Q.event_id
    GROUP BY Q.event_id, Q.person_id, Q.start_date, Q.end_date, Q.op_start_date, Q.op_end_date
  ) MG -- matching groups
{@ruleTotal != 0}?{
  -- the matching group with all bits set ( POWER(2,# of inclusion rules) - 1 = inclusion_rule_mask
  WHERE (MG.inclusion_rule_mask = POWER(cast(2 as bigint),@ruleTotal)-1)
}
)
select event_id, person_id, start_date, end_date, op_start_date, op_end_date
into #included_events
FROM cteIncludedEvents Results
@ResultLimitFilter
;
```
added subselect with distinct for #qualified_events . Since both #qualified_events and #inclusionRuleCohorts don't have duplicates #included_events should not have duplicates.

This should solve?

**Comment by chrisknoll** [comment]
Hey, @gowthamrao ,

Distinct won't have any effect on those queries, and here's why:

Each primary event has a person_id and event_id column which makes it unique to all other records.  The queries are carefully crafted to never insert dupes into the #qualified_events temp table because there's a binary arithmetic operation to efficiently figure out if an event passes all inclusion criteria:

```
   SUM(coalesce(POWER(cast(2 as bigint), I.inclusion_rule_id), 0)) as inclusion_rule_mask
...
...
  FROM  (
...
...
...
 ) MG -- matching groups
WHERE (MG.inclusion_rule_mask = POWER(cast(2 as bigint),@ruleTotal)-1)
```
What is this POWER() call doing?  It's finding the rows (events) where if you add up the ruleId^2 from each event, if you get totalRules^2 - 1, then the event satisfies all the rules.

The #qualified_events table can NOT have dupes in it, otherwise you'd end up with something like this:
3 inclusion rules:
001
010
100
----
111 = 7 = 2^3 = 2^(RuleCount - 1)

if we had some dupe in that #qualified_events:
001
001
010
100
____
1000 = 8!  the dupe 001 entry fowled up the 'matching criteria' calculation.

So, this is all to say:  The #qualified_events and #included events work properly they way they are coded, and they can't change because they are specifically constructed so that they perform the binary arithmetic properly.  

For keeping backwards compatibility, we just need a way to allow the users that specified 'earliest event per person' to get one event per person (ie: row_number() vs. dense_rank()).  I think that we can leave the individual criteria queries that use dense_rank to find first() alone, because when they trickle up to the primary event query, they can be limited to 1 per person at that point (and gives us the added benefit of allowing 'ties' to be evaluated at first, but then return the first tie).

So, short term, I propose switching back the primary_events and qualifying_events limiter to use row_number().  Longer term, we need a better way to get 'person-centric' report statistics but I think that's a more complicated exercise, but we should talk about the details in this thread specifically.  

I'm meeting with @pbr6cornell tomorrow to discuss the impact of the dense_rank(), the compromise of using row_number() for 'earliest event per person' queries, and if all goes well, I'll make a hot-fix release of the library.  then we can dig into the meat of how to get more meaningful statistics out of #qualified_events and #included_events while having the goodness of dense_rank() allowing us to evaluate more than 1 event that occurs on the same day.  But that second step is something that will probably be post WebAPI 2.2 release and OHDSI symposium 2017.

**Comment by gowthamrao** [comment]
Thanks. Will the hot fix impact the functionality of restricting to the same visit_occurrence_id?

**Comment by chrisknoll** [comment]
Hey, @gowthamrao ,
  You're correct abut using desne_rank() and distinct to remove duplicate rows, but after talking with @pbr6cornell , we're thinking about using that technique at an earlier phase of the cohort generation to get the initial events narrowed down to the unique set of events, making statistics calculation more straight forward.  The details of this will be posted in a separate issue, but for purposes of this issue and the next release of atlas, we're going to revert the dense_rank() to row_number in the use of 'ordinal' so that we can limit rows to 1 per person.  I'll make a quick PR and change to the queries that define the ordinal column so that we have the prior behavior about selecting 'first' and 'earliest/latest'.  This won't have any impact on same-visit queries or era-collapsing logic.

I'll post the new issue shortly, but I wanted to take care of the immediate issue first.

-Chris
